from enum import Enum


class ExceptionType(str, Enum):
    """
    Canonical Session 7 reconciliation exception taxonomy.
    """

    MISSING_BANK_RECORD = "MISSING_BANK_RECORD"
    AMOUNT_MISMATCH = "AMOUNT_MISMATCH"
    DUPLICATE_BANK_TRANSACTION = "DUPLICATE_BANK_TRANSACTION"
    UNKNOWN_REFERENCE = "UNKNOWN_REFERENCE"
    AMBIGUOUS_MATCH = "AMBIGUOUS_MATCH"
    PARTIAL_SETTLEMENT = "PARTIAL_SETTLEMENT"
    COMBINED_SETTLEMENT = "COMBINED_SETTLEMENT"
    DATE_MISMATCH = "DATE_MISMATCH"
    MISSING_PAYMENT = "MISSING_PAYMENT"
    MISSING_SETTLEMENT = "MISSING_SETTLEMENT"